FROM golang:1.19-alpine AS build
RUN apk add git

WORKDIR /src/
COPY service mongo /src/
RUN go mod init github.com/rovechkin1/message-sign
RUN go mod tidy
RUN go build -o /bin/service service/cmd/main.go
RUN go build -o /bin/record-generator mongo/record_generator.go


FROM scratch
WORKDIR /app/
COPY --from=build /bin/service /app/service
COPY --from=build /bin/record-generator /app/record-generator

ENTRYPOINT ["/app/service"]