FROM golang:1.19-alpine AS build
RUN apk add git

ENV GO111MODULE=on
WORKDIR /src/
COPY service  /src/service
COPY mongo  /src/mongo
COPY go.mod go.sum /src/

RUN CGO_ENABLED=0  go build -o /app/service service/cmd/main.go
RUN CGO_ENABLED=0 go build -o /app/record-generator mongo/record_generator.go


FROM alpine
RUN apk add curl vim git bash
WORKDIR /app/
COPY --from=build /app/service /app/service
COPY --from=build /app/record-generator /app/record-generator

#ENTRYPOINT ["/app/service"]